{{- if and .Values.iceberg.enabled (eq .Values.iceberg.provider "minio") }}
apiVersion: v1
kind: Service
metadata:
  name: minio-api
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  clusterIP: None
  #type: {{ .Values.iceberg.minio.service.api.type | default "ClusterIP" }}
  # publishNotReadyAddresses: true
  ports:
    - name: minio-apiport
      port: {{ .Values.iceberg.minio.service.api.port | default 9000 }}
      targetPort: minio-api
  selector:
    {{- include "resurface.selectorLabels" . | nindent 4 }}
    iceberg.resurface.io/role: minio
{{- if .Values.iceberg.minio.service.console.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  type: {{ .Values.iceberg.minio.service.console.type | default "ClusterIP" }}
  ports:
    - name: minio-webport
      port: {{ .Values.iceberg.minio.service.console.port | default 9001 }}
      targetPort: minio-web
  selector:
    {{- include "resurface.selectorLabels" . | nindent 4 }}
    iceberg.resurface.io/role: minio
{{- end }}
{{- end }}
