{{- if default "" .Values.provider | eq "aws" | and .Values.sniffer.enabled .Values.sniffer.vpcmirror.enabled .Values.sniffer.vpcmirror.autosetup.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: vnis-config
data:
  vnis: ""
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "resurface.fullname" . }}-mirror-maker
spec:
  schedule: {{ .Values.sniffer.vpcmirror.autosetup.schedule | default "0 * * * *" | quote }}
  jobTemplate:
    spec:
    {{- include "resurface.jobspec.aws.mirrormaker" . | nindent 6 }}
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "resurface.fullname" . }}-mirror-maker-hook
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  {{- include "resurface.jobspec.aws.mirrormaker" . | nindent 2 }}
      restartPolicy: Never
{{- end -}}
