{{- if and .Values.qa.enabled .Values.qa.simulator.enabled -}}
{{- $version := default "3.6.1" .Values.qa.simulator.version -}}
{{- $initialSleepSeconds := default 180 .Values.qa.simulator.sleep.init | int -}}
{{- $workload := default "RestSmall2" .Values.qa.simulator.workload -}}
{{- $host := printf "worker.%s" .Release.Namespace -}}
{{- $port := "7701" -}}
{{- if not .Values.ingress.tls.enabled | and .Values.ingress.enabled .Values.ingress.controller.enabled -}}
  {{- $host = printf "%s.%s" (include "kubernetes-ingress.fullname" (index .Subcharts "kubernetes-ingress")) .Release.Namespace -}}
  {{- $port = "80" -}}
{{- end -}}
{{- $host = default $host .Values.qa.simulator.host -}}
{{- $port = default $port .Values.qa.simulator.port -}}
{{- $limitMessages := default 0 .Values.qa.simulator.limit.messages | int -}}
{{- $limitMillis := default 0 .Values.qa.simulator.limit.millis | int -}}
{{- $clockSkewDays := default 0 .Values.qa.simulator.clockskew | int -}}
{{- $sleepPerBatch := default 0 .Values.qa.simulator.sleep.batch | int -}}
{{- $batchSize := default 128 .Values.qa.simulator.batchsize | int -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "resurface.fullname" . }}-simulator
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: simulator
      labels:
        {{- include "resurface.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: resurface-sa
      securityContext:
        runAsUser: 0
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: simulator
          image: eclipse-temurin:17-jre
          command:
            - "/bin/sh"
            - "-c"
            - "wget https://dl.cloudsmith.io/public/resurfaceio/public/maven/io/resurface/resurfaceio-simulator/{{ $version }}/resurfaceio-simulator-{{ $version }}.jar && echo 'wait {{ div $initialSleepSeconds 60 }} minutes' && sleep {{ $initialSleepSeconds }} && echo 'done' && java -DWORKLOAD={{ $workload }} -DHOST={{ $host }} -DPORT={{ $port }} -DLIMIT_MESSAGES={{ $limitMessages }} -DLIMIT_MILLIS={{ $limitMillis }} -DCLOCK_SKEW_DAYS={{ $clockSkewDays }} -DSLEEP_PER_BATCH={{ $sleepPerBatch }} -DBATCH_SIZE={{ $batchSize }} -Xmx512M -jar resurfaceio-simulator-{{ $version }}.jar"
{{- end -}}
