{{- if and .Values.iceberg.enabled .Values.qa.enabled .Values.qa.simulator.enabled -}}
{{- $version := default "3.5.7" .Values.qa.simulator.version -}}
{{- $initialSleepSeconds := default 180 .Values.qa.simulator.sleep.init -}}
{{- $workload := default "RestSmall2" .Values.qa.simulator.workload -}}
{{- $host := default "worker.resurface" .Values.qa.simulator.host -}}
{{- $port := default "7701" .Values.qa.simulator.port -}}
{{- $limitMessages := default 0 .Values.qa.simulator.limit.messages -}}
{{- $limitMillis := default 0 .Values.qa.simulator.limit.millis -}}
{{- $sleepPerBatch := default 0 .Values.qa.simulator.sleep.batch -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resurface.fullname" . }}-simulator
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "resurface.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: simulator
      labels:
        {{- include "resurface.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: resurface-sa
      securityContext:
        runAsUser: 0
      containers:
        - name: simulator
          image: eclipse-temurin:17-jre
          command:
            - "/bin/sh"
            - "-c"
            - "wget https://dl.cloudsmith.io/public/resurfacelabs/public/maven/io/resurface/resurfaceio-simulator/{{ $version }}/resurfaceio-simulator-{{ $version }}.jar && echo 'wait {{ div $initialSleepSeconds 60 }} minutes' && sleep {{ $initialSleepSeconds }} && echo 'done' && java -DWORKLOAD={{ $workload }} -DHOST={{ $host }} -DPORT={{ $port }} -DLIMIT_MESSAGES={{ $limitMessages }} -DLIMIT_MILLIS={{ $limitMillis }} -DSLEEP_PER_BATCH={{ $sleepPerBatch }} -Xmx512M -jar resurfaceio-simulator-{{ $version }}.jar"
{{- end -}}
