version: '3.2'

services:
  coordinator:
    container_name: resurface_coordinator
    image: docker.resurface.io/release/resurface:2.4.0-beta2
    ports:
      - '4000:4000'
      - 4001
    tmpfs:
      - /db

  workerA:
    container_name: resurface_workerA
    image: docker.resurface.io/release/resurface-worker:2.4.0-beta2
    ports:
      - 4000
      - 4001
    tmpfs:
      - /db

  haproxy:
    container_name: resurface_haproxy
    image: eeacms/haproxy
    depends_on:
      - coordinator
      - workerA
    ports:
      - '4001:4001'
    environment:
      FRONTEND_PORT: "4001"
      BACKENDS: "coordinator workerA"
      BACKENDS_PORT: "4001"
      DNS_ENABLED: "True"
      HTTPCHK: "GET /"
      INTER: "5s"
      LOG_LEVEL: "info"
