apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-coordinator-config
  namespace: {{ .Release.Namespace }}
data:
  config.properties: |
    coordinator=true
    discovery.uri=http://localhost:7700
    {{ if .Values.ingress.tls.enabled -}}
    http-server.process-forwarded=true
    http-server.authentication.allow-insecure-over-http=true
    {{- include "resurface.config.auth" . | nindent 4 -}}
    {{- end }}
    node-scheduler.include-coordinator=true
    {{- include "resurface.config.common" . | nindent 4 }}
{{- if and .Values.auth.enabled .Values.auth.passwdfile.enabled }}
  password-authenticator.properties: |
    password-authenticator.name=file
    file.password-file=etc/creds/password.db
---
apiVersion: v1
kind: Secret
metadata:
  name: trino-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password.db: {{ include "resurface.auth.creds" . }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-worker-config
  namespace: {{ .Release.Namespace }}
data:
  config.properties: |
    coordinator=false
    discovery.uri=http://coordinator:7700
<<<<<<< HEAD
    {{- include "resurface.config.common" . | nindent 4 }}
=======
    {{- include "resurface.config.common" . | nindent 4 }}
>>>>>>> origin/v3.1.x
