apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resurface.fullname" . }}
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "resurface.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "resurface.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: resurface-entitlement
      containers:
        - name: {{ .Chart.Name }}
          image: docker.resurface.io/release/resurface:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: db
              containerPort: {{ .Values.service.port.apiExplorer }}
              protocol: TCP
            - name: fluke
              containerPort: {{ .Values.service.port.flukeServer }}
              protocol: TCP
