apiVersion: v1
kind: Secret
metadata:
  name: resurface-entitlement
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
