apiVersion: v1
kind: Secret
metadata:
  name: resurface-entitlement
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "%s%s%s%s%s" "{\"auths\":{\"docker.resurface.io\":{\"username\":\"resurfacelabs/release\",\"password\":" (.Values.entitlementToken | quote) ",\"auth\":" (printf "%s:%s" "resurfacelabs/release" .Values.entitlementToken | b64enc | quote) "}}}" | b64enc }}
