{{- if .Values.service.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resurface-ingress
  annotations:
    haproxy.org/load-balance: "roundrobin"
    haproxy.org/path-rewrite: /fluke/(.*) /\1
    {{- if and .Values.service.ingress.tls.enabled .Values.service.ingress.tls.autoissue.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt{{ if .Values.service.ingress.tls.autoissue.staging }}-staging{{ end }}
    {{- end }}
spec:
  ingressClassName: haproxy
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coordinator
                port:
                  number: 7700
          - path: /fluke
            pathType: Prefix
            backend:
              service:
                name: worker
                port:
                  number: 7701
      {{- if .Values.service.ingress.tls.enabled }}
      host: {{ .Values.service.ingress.tls.host }}
      {{- end }}
  {{- if .Values.service.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.service.ingress.tls.byoc.secretName | default "resurface-tls" }}
      hosts:
        - {{ .Values.service.ingress.tls.host }}
  {{- end }}
{{- end }}
