{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.autoissue.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "resurface.fullname" . }}-letsencrypt{{ if .Values.ingress.tls.autoissue.staging }}-staging{{ end }}
spec:
  acme:
    email: {{ .Values.ingress.tls.autoissue.email }}
    server: https://acme{{ if .Values.ingress.tls.autoissue.staging }}-staging{{ end }}-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ include "resurface.fullname" . }}-pk
    solvers:
      - http01:
          ingress:
            name: {{ include "resurface.fullname" . }}-ingress
{{- end }}
