{{- if include "tls.helper.mode" . | eq "auto" | and .Values.ingress.enabled .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.ingress.tls.autoissue.staging | ternary "-staging" "" | print (include "resurface.fullname" .) "-letsencrypt" }}
spec:
  acme:
    email: {{ required "E-mail address is required for TLS autoissuing process" .Values.ingress.tls.autoissue.email }}
    server: {{ .Values.ingress.tls.autoissue.staging | ternary "-staging" "" | printf "https://acme%s-v02.api.letsencrypt.org/directory" }}
    privateKeySecretRef:
      name: {{ include "resurface.fullname" . | printf "%s-pk" }}
    solvers:
      - http01:
          ingress:
            name: {{ include "resurface.fullname" . | printf "%s-ingress" }}
            podTemplate:
              spec:
                tolerations:
                  {{- toYaml .Values.tolerations | nindent 18 }}
{{- end }}
