apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.apiExplorer.type | default LoadBalancer }}
  ports:
    - port: {{ .Values.service.apiExplorer.port }}
      targetPort: db
  selector:
    {{- include "resurface.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: fluke-svc
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.flukeServer.type | default ClusterIP }}
  ports:
    - port: {{ .Values.service.flukeServer.port }}
      targetPort: fluke
  selector:
    {{- include "resurface.selectorLabels" . | nindent 4 }}
