apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  {{- if or .Values.service.ingress.enabled (eq .Values.service.apiExplorer.type "Headless") }}
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.apiExplorer.type | default "LoadBalancer" }}
  {{- end }}
  ports:
    - port: {{ .Values.service.apiExplorer.port }}
      targetPort: db
  selector:
    {{- include "resurface.selectorLabels" . | nindent 4 }}
    db.resurface.io/role: "coordinator"
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.flukeServer.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.flukeServer.port }}
      targetPort: fluke
  selector:
    {{- include "resurface.selectorLabels" . | nindent 4 }}
