apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  {{- if or .Values.ingress.enabled (quote .Values.custom.service.apiexplorer.type | eq "\"Headless\"") }}
  clusterIP: None
  {{- else }}
  type: {{ .Values.custom.service.apiexplorer.type | default "LoadBalancer" }}
  {{- end }}
  ports:
    - name: db-svcport
      port: {{ .Values.custom.service.apiexplorer.port | default 7700 }}
      targetPort: db
  selector:
    {{- include "resurface.selectorLabels" . | nindent 4 }}
    db.resurface.io/role: coordinator
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  type: {{ .Values.custom.service.flukeserver.type | default "ClusterIP" }}
  ports:
    - name: fluke-svcport
      port: {{ .Values.custom.service.flukeserver.port | default 7701 }}
      targetPort: fluke
  selector:
    {{- include "resurface.selectorLabels" . | nindent 4 }}
