apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  {{- if or .Values.service.ingress.enabled (eq .Values.service.apiexplorer.type "Headless") }}
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.apiexplorer.type | default "LoadBalancer" }}
  {{- end }}
  ports:
    - name: db-svcport
      port: {{ .Values.service.apiexplorer.port }}
      targetPort: db
  selector:
    {{- include "resurface.selectorLabels" . | nindent 4 }}
    db.resurface.io/role: "coordinator"
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.flukeserver.type | default "ClusterIP" }}
  ports:
    - name: fluke-svcport
      port: {{ .Values.service.flukeserver.port }}
      targetPort: fluke
  selector:
    {{- include "resurface.selectorLabels" . | nindent 4 }}
