{{- if .Values.multinode.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "resurface.fullname" . }}-worker
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  serviceName: worker
  podManagementPolicy: Parallel
  replicas: {{ .Values.multinode.workers }}
  selector:
    matchLabels:
      {{- include "resurface.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "resurface.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: resurface-entitlement
      containers:
        - name: worker
          image: docker.resurface.io/release/resurface-worker:{{ .Chart.AppVersion }}
          ports:
            - name: fluke
              containerPort: 7701
          {{- include "resurface.containerConfig" . | nindent 10 }}
          volumeMounts:
            - name: {{ include "resurface.fullname" . }}-{{ if .Values.custom.storage.volatile }}tmpfs{{ else }}pvc{{ end }}
              mountPath: /db
  {{- if .Values.custom.storage.volatile }}
      volumes:
        - name: {{ include "resurface.fullname" . }}-tmpfs
          emptyDir:
            medium: "Memory"
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "resurface.fullname" . }}-pvc
      spec:
        storageClassName: {{ include "resurface.getProvidedClass" . }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.custom.storage.workerSize }}
  {{- end }}
{{- end -}}
