apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "resurface.fullname" . }}-coordinator
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  serviceName: coordinator
  replicas: 1
  selector:
    matchLabels:
      {{- include "resurface.selectorLabels" . | nindent 6 }}
      db.resurface.io/role: "coordinator"
  template:
    metadata:
      labels:
        {{- include "resurface.selectorLabels" . | nindent 8 }}
        db.resurface.io/role: "coordinator"
    spec:
      imagePullSecrets:
        - name: resurface-entitlement
      containers:
        - name: coordinator
          image: docker.resurface.io/release/resurface:{{ .Chart.AppVersion }}
          ports:
            - name: db
              containerPort: 7700
            - name: fluke
              containerPort: 7701
          {{- include "resurface.containerConfig" . | nindent 10 }}
          volumeMounts:
            - name: {{ include "resurface.fullname" . }}-{{ if .Values.storage.volatile }}tmpfs{{ else }}pvc{{ end }}
              mountPath: /db
  {{- if .Values.storage.volatile }}
      volumes:
        - name: {{ include "resurface.fullname" . }}-tmpfs
          emptyDir:
            medium: "memory"
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "resurface.fullname" . }}-pvc
      spec:
        storageClassName: {{ include "resurface.getProvidedClass" . }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.coordinatorSize }}
  {{- end }}
