{{- if .Values.multinode.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "resurface.fullname" . }}-worker
  labels:
    {{- include "resurface.labels" . | nindent 4 }}
spec:
  serviceName: worker
  podManagementPolicy: Parallel
  replicas: {{ .Values.multinode.workers }}
  selector:
    matchLabels:
      {{- include "resurface.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "resurface.config.worker" . | sha256sum }}
      labels:
        {{- include "resurface.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: resurface-sa
      volumes:
        - name: config-volume
          configMap:
            name: trino-worker-config
            items:
              - key: config.properties
                path: config.properties
      containers:
        - name: worker
          image: resurfaceio/resurface-worker:{{ .Chart.AppVersion }}
          ports:
            - name: fluke
              containerPort: 7701
          volumeMounts:
            - name: config-volume
              mountPath: /opt/trino/etc/config.properties
              subPath: config.properties
            - name: {{ include "resurface.fullname" . }}-pvc
              mountPath: /db
  {{- include "resurface.resources" . }}
{{- end }}
