{{- if and (and (and .Values.service.ingress.enabled .Values.service.ingress.tls.enabled) (not .Values.service.ingress.tls.autoissue.enabled)) (eq .Values.service.ingress.tls.byoc.secretname nil) }}
apiVersion: v1
kind: Secret
metadata:
  name: resurface-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.service.ingress.tls.byoc.cert }}
  tls.key: {{ .Values.service.ingress.tls.byoc.key }}
{{- end }}
