{{- if and (and (and .Values.service.ingress.enabled .Values.service.ingress.tls.enabled) (not .Values.service.ingress.tls.autoissue.enabled)) (eq .Values.service.ingress.tls.byoc.secretName nil) }}
apiVersion: v1
kind: Secret
metadata:
  name: resurface-tls
type: kubernetes.io/tls
data:
  tls.crt:
  tls.key:
{{- end }}
