image:
  pullSecrets:
    - name: resurface-entitlement

sidecars:
  - name: netsniffer
    image: docker.resurface.io/release/network-sniffer:1.0.0
    imagePullPolicy: Always
    env:
    - name: USAGE_LOGGERS_URL
      value: "http://resurface:7701/message"
    - name: USAGE_LOGGERS_RULES
      value: include debug
    - name: APP_PORT
      value: 80
