version: '3.2'

services:
  coordinator:
    image: resurfaceio/resurface:3.4.21
    ports:
      - 7700
      - 7701
    tmpfs:
      - /db

  worker:
    image: resurfaceio/resurface-worker:3.4.21
    ports:
      - 7700
      - 7701
    tmpfs:
      - /db

  coordinator_proxy:
    image: eeacms/haproxy
    depends_on:
      - coordinator
    ports:
      - '7700:7700'
    environment:
      FRONTEND_PORT: "7700"
      BACKENDS: "coordinator"
      BACKENDS_PORT: "7700"
      DNS_ENABLED: "True"
      HTTPCHK: "GET /"
      INTER: "5s"
      LOG_LEVEL: "info"

  fluke_proxy:
    image: eeacms/haproxy
    depends_on:
      - coordinator
      - worker
    ports:
      - '7701:7701'
    environment:
      FRONTEND_PORT: "7701"
      BACKENDS: "coordinator worker"
      BACKENDS_PORT: "7701"
      DNS_ENABLED: "True"
      HTTPCHK: "GET /"
      INTER: "5s"
      LOG_LEVEL: "info"
