version: '3.2'

services:
  coordinator:
    image: resurfaceio/resurface-iceberg:3.5.0p22
    environment:
      - DB_HEAP=8g
      - DB_SIZE=9g
      - DB_SLABS=3
      - SHARD_SIZE=3g
      - HIVE_S3_URL=http://192.168.168.12:9000
      - HIVE_S3_USER=minio
      - HIVE_S3_SECRET=minio123
      - HIVE_S3_LOCATION=s3a://iceberg.resurface/
      - POLLING_CYCLE=fast
      - POLLING_ICEBERG_MILLIS=20000
    ports:
      - 7700
      - 7701
    tmpfs:
      - /db

  worker:
    image: resurfaceio/resurface-iceberg-worker:3.5.0p22
    environment:
      - DB_HEAP=8g
      - DB_SIZE=9g
      - DB_SLABS=3
      - SHARD_SIZE=3g
      - HIVE_S3_URL=http://192.168.168.12:9000
      - HIVE_S3_USER=minio
      - HIVE_S3_SECRET=minio123
      - HIVE_S3_LOCATION=s3a://iceberg.resurface/
    ports:
      - 7700
      - 7701
    tmpfs:
      - /db

  coordinator_proxy:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - coordinator
    ports:
      - '7700:7700'
    environment:
      FRONTEND_PORT: "7700"
      BACKENDS: "coordinator"
      BACKENDS_PORT: "7700"
      DNS_ENABLED: "True"
      HTTPCHK: "GET /"
      INTER: "5s"
      LOG_LEVEL: "info"

  fluke_proxy:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - coordinator
      - worker
    ports:
      - '7701:7701'
    environment:
      FRONTEND_PORT: "7701"
      BACKENDS: "coordinator worker"
      BACKENDS_PORT: "7701"
      DNS_ENABLED: "True"
      HTTPCHK: "GET /"
      INTER: "5s"
      LOG_LEVEL: "info"
