version: '3.2'

services:
  minio:
    container_name: minio
    image: 'minio/minio:latest'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data

  coordinator:
    container_name: resurface
    image: resurfaceio/resurface-iceberg:3.5.12
    depends_on:
      - minio
    environment:
      - DB_HEAP=8g
      - DB_SIZE=9g
      - DB_SLABS=3
      - POLLING_CYCLE=fast
      - SHARD_SIZE=3g
      - TZ=America/Denver
      - ICEBERG_FILE_FORMAT=ORC
      - ICEBERG_COMPRESSION_CODEC=ZSTD
      - ICEBERG_SIZE_MAX=1000g
      - ICEBERG_SIZE_RESERVED=50g
      - ICEBERG_POLLING_MILLIS=20000
      - ICEBERG_S3_URL=http://minio:9000
      - ICEBERG_S3_USER=minio
      - ICEBERG_S3_SECRET=minio123
      - ICEBERG_S3_LOCATION=s3a://iceberg.resurface/
    ports:
      - 7700
      - 7701
    volumes:
      - resurface-coordinator:/db

  workerA:
    container_name: resurface-workerA
    image: resurfaceio/resurface-iceberg-worker:3.5.12
    depends_on:
      - coordinator
    environment:
      - DB_HEAP=8g
      - DB_SIZE=9g
      - DB_SLABS=3
      - SHARD_SIZE=3g
      - TZ=America/Denver
      - ICEBERG_FILE_FORMAT=ORC
      - ICEBERG_COMPRESSION_CODEC=ZSTD
      - ICEBERG_POLLING_MILLIS=20000
      - ICEBERG_S3_URL=http://minio:9000
      - ICEBERG_S3_USER=minio
      - ICEBERG_S3_SECRET=minio123
      - ICEBERG_S3_LOCATION=s3a://iceberg.resurface/
    ports:
      - 7700
      - 7701
    volumes:
      - resurface-workerA:/db

  workerB:
    container_name: resurface-workerB
    image: resurfaceio/resurface-iceberg-worker:3.5.12
    depends_on:
      - coordinator
    environment:
      - DB_HEAP=8g
      - DB_SIZE=9g
      - DB_SLABS=3
      - SHARD_SIZE=3g
      - TZ=America/Denver
      - ICEBERG_FILE_FORMAT=ORC
      - ICEBERG_COMPRESSION_CODEC=ZSTD
      - ICEBERG_POLLING_MILLIS=20000
      - ICEBERG_S3_URL=http://minio:9000
      - ICEBERG_S3_USER=minio
      - ICEBERG_S3_SECRET=minio123
      - ICEBERG_S3_LOCATION=s3a://iceberg.resurface/
    ports:
      - 7700
      - 7701
    volumes:
      - resurface-workerB:/db

  coordinator_proxy:
    container_name: coordinator-proxy
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - coordinator
    ports:
      - '7700:7700'
    environment:
      FRONTEND_PORT: "7700"
      BACKENDS: "coordinator"
      BACKENDS_PORT: "7700"
      DNS_ENABLED: "True"
      HTTPCHK: "GET /"
      INTER: "5s"
      LOG_LEVEL: "info"

  fluke_proxy:
    container_name: fluke-proxy
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - coordinator
      - workerA
      - workerB
    ports:
      - '7701:7701'
    environment:
      FRONTEND_PORT: "7701"
      BACKENDS: "coordinator workerA workerB"
      BACKENDS_PORT: "7701"
      DNS_ENABLED: "True"
      HTTPCHK: "GET /"
      INTER: "5s"
      LOG_LEVEL: "info"

volumes:
  minio-data:
    driver: local
  resurface-coordinator:
    driver: local
  resurface-workerA:
    driver: local
  resurface-workerB:
    driver: local
