{{- if .Values.sniffer.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resurface.fullname" . }}-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "services"]
  verbs: ["get", "watch", "list"]
{{ if default "" .Values.provider | eq "aws" | and .Values.sniffer.vpcmirror.enabled .Values.sniffer.vpcmirror.autosetup.enabled -}}
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["vnis-config"]
  verbs: ["get","patch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "patch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
{{- end }}
{{- end }}
