{{- if .Values.provider | default "" | eq "ibm-openshift" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resurface.fullname" . | printf "%s-scc-binding" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.custom.scc | default "nonroot" | printf "system:openshift:scc:%s" }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resurface.fullname" . | printf "%s-sa" }}
    namespace: {{ .Release.Namespace }}
  {{- if .Values.minio.enabled }}
  - kind: ServiceAccount
    name: {{ .Values.minio.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end -}}