apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "resurface-scc"
  labels:
    app: "resurface-scc"
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - resurface-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use