{{- if and .Values.iceberg.enabled .Values.iceberg.s3.enabled (empty .Values.iceberg.s3.aws.accesskey | not) (empty .Values.iceberg.s3.aws.secretkey | not) -}}
apiVersion: v1
kind: Secret
metadata:
  name: resurface-s3-creds
type: Opaque
data:
  rootUser: {{ .Values.iceberg.s3.aws.accesskey | toString | b64enc }}
  rootPassword: {{ .Values.iceberg.s3.aws.secretkey| toString | b64enc }}
{{- end -}}
