{{- if and (and (and .Values.ingress.enabled .Values.ingress.tls.enabled) (not .Values.ingress.tls.autoissue.enabled)) (empty .Values.ingress.tls.byoc.secretname) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resurface.fullname" . }}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.byoc.cert }}
  tls.key: {{ .Values.ingress.tls.byoc.key }}
{{- end }}
