{{- if include "tls.helper.mode" . | eq "certkey-byoc" | and .Values.ingress.enabled .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resurface.fullname" . }}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.byoc.cert }}
  tls.key: {{ .Values.ingress.tls.byoc.key }}
{{- end }}
