theme: jekyll-theme-cayman

title: resurface.io
description: |
  Continuous API Intelligence.
  Dive deeper and find out how your APIs are being used (and misused).
  See API attacks, failures, and quality issues at runtime.
  Resurface provides observability into APIs for both quality and security.
  Never guess what's going on with your APIs again.
