apiVersion: v2
name: resurface
version: 3.6.0-0.1.0
type: application
description: Resurface discovers and alerts on quality and security signatures in your API traffic.
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - kind: added
      description: Cronjob to update AWS VPC Traffic Mirror sessions
    - kind: changed
      description: Upgrade network-sniffer image to 1.3.0
keywords:
  - API
  - HTTP
  - Triage
  - Security
  - Observability
  - Logs
  - Monitoring
  - Troubleshooting
  - Alerts
home: https://resurface.io
dependencies:
  - name: kubernetes-ingress
    version: "1.29.2"
    repository: https://haproxytech.github.io/helm-charts
    condition: ingress.controller.enabled
  - name: minio
    version: "5.0.7"
    repository: https://charts.min.io/
    condition: minio.enabled
maintainers:
  - name: Ramón Márquez
    email: ramon@resurface.io
  - name: Rob Dickinson
    email: rob@resurface.io
sources:
  - https://github.com/resurfaceio
icon: https://raw.githubusercontent.com/resurfaceio/insomnia-plugin/master/assets/plugin/icon-alt.svg
appVersion: 3.5.4
