apiVersion: v2
name: resurface
version: 3.2.0
description: |+
  Resurface discovers and alerts on quality and security signatures in your API traffic.
  3.2.0 — 2022/07/28
  Added
    · Change log
    · Support for data capture using native AWS VPC mirroring.
    · Support for data capture from both Azure APIM and AWS API Gateway, using event stream consumer apps for both Azure Event Hubs and AWS Kinesis Data Streams.
    · HAProxy ingress controller subchart as an optional dependency.
  Changed
    · Resurface container to version 3.2.2 (Trino 391).
    · Network sniffer to version 1.2.1 (GoReplay 1.3.3-Resurface).
  Fixed
    · README examples.
  Security
    · Use secrets to store sensitive values for consumer applications.

type: application
keywords:
  - API
  - HTTP
  - Triage
  - Security
  - Observability
  - Logs
  - Monitoring
  - Troubleshooting
  - Alerts
home: https://resurface.io
dependencies:
  - name: kubernetes-ingress
    version: "1.22.4"
    repository: https://haproxytech.github.io/helm-charts
    condition: ingress.enabled
maintainers:
  - name: Ramón Márquez
    email: ramon@resurface.io
  - name: Rob Dickinson
    email: rob@resurface.io
sources:
  - https://github.com/resurfaceio
icon: https://raw.githubusercontent.com/resurfaceio/insomnia-plugin/master/assets/plugin/icon-alt.svg
appVersion: 3.2.2
