apiVersion: v2
name: resurface
version: 3.1.0
description: Resurface discovers and alerts on quality and security signatures in your API traffic.
type: application
keywords:
  - API
  - HTTP
  - Triage
  - Security
  - Observability
  - Logs
  - Monitoring
  - Troubleshooting
  - Alerts
home: https://resurface.io
sources:
  - https://github.com/resurfaceio
icon: https://raw.githubusercontent.com/resurfaceio/insomnia-plugin/master/assets/plugin/icon-alt.svg
appVersion: 3.1.11
