apiVersion: v2
name: resurface
version: 3.6.7
type: application
description: Resurface discovers and alerts on quality and security signatures in your API traffic.
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: added
      description: Support to route MinIO console through ingress controller
    - kind: added
      description: Support for sql.forced-session-time-zone Trino config
    - kind: changed
      description: Upgrade Resurface image to 3.6.42
    - kind: changed
      description: Upgrade HAProxy dependency chart to 1.35.5
    - kind: changed
      description: Upgrade MinIO dependency chart to 5.0.14
keywords:
  - API
  - HTTP
  - Triage
  - Security
  - Observability
  - Logs
  - Monitoring
  - Troubleshooting
  - Alerts
home: https://resurface.io
dependencies:
  - name: kubernetes-ingress
    version: "1.35.5"
    repository: https://haproxytech.github.io/helm-charts
    condition: ingress.controller.enabled
  - name: minio
    version: "5.0.14"
    repository: https://charts.min.io/
    condition: minio.enabled
maintainers:
  - name: Ramón Márquez
    email: ramon@resurface.io
  - name: Rob Dickinson
    email: rob@resurface.io
sources:
  - https://github.com/resurfaceio
icon: https://raw.githubusercontent.com/resurfaceio/insomnia-plugin/master/assets/plugin/icon-alt.svg
appVersion: 3.6.42
