apiVersion: v2
name: resurface
version: 2.2.0
description: >
    Resurface can help with failure triage and root cause, threat and risk identification,
    and simply just knowing how your APIs are being used. It identifies what's important
    in your API data, and can send warnings and alerts in real-time for fast action.
type: application
keywords:
  - API
  - HTTP
  - Triage
  - Security
  - Observability
  - Logs
  - Monitoring
  - Troubleshooting
  - Alerts
home: https://resurface.io
sources:
  - https://github.com/resurfaceio
icon: https://raw.githubusercontent.com/resurfaceio/insomnia-plugin/master/assets/plugin/icon-alt.svg
appVersion: 3.0.41
