# Default values for Resurface
# This is a YAML-formatted file.

provider:

ingress:
  enabled: true
  controller:
    enabled: true
  importer:
    expose: true
    path: "/fluke"
  tls:
    enabled: false
    host: 
    autoissue:
      enabled: true
      staging: true
      email: 
    byoc:
      secretname:

auth:
  enabled: false
  basic:
    enabled: false
    credentials:
      - username: 
        password: 
  jwt:
    enabled: false
    jwksurl: 
  oauth2:
    enabled: false
    issuer: 
    authurl: 
    tokenurl: 
    jwksurl: 
    userinfourl: 
    clientid: 
    clientsecret: 

multinode:
  enabled: false
  workers: 1

iceberg:
  enabled: false
  minio:
    enabled: true
    size:
    nodes: 1
    service:
      console:
        enabled: false
        type: LoadBalancer
        port: 80
      api:
        type:
        port:
    secrets:
      accesskey:
      secretkey:
    bucketcreator:
      enabled: true
  s3:
    enabled: false
    awsregion:
    bucketname: iceberg.resurface
    accesskey:
    secretkey:
  config:
    pollingmillis:
    compression:
    fileformat:

custom:
  service:
    apiexplorer:
      port:
      type:
    flukeserver:
      port:
      type:
  resources:
    cpu:
    memory:
  config:
    dbsize:
    dbheap:
    dbslabs:
    shardsize:
    pollingcycle:
    tz:
  storage:
    size:
    classname:

sniffer:
  enabled: false
  discovery:
    enabled: false
    skip:
      ns: [ "kube-system" ]
      svc: [ "kubernetes" ]
  services:
  pods:
  labels:
  vpcmirror:
    enabled: false
    vnis:
    ports:
  logger:
    enabled: true
    rules: |
      include default
      skip_compression

consumer:
  azure:
    enabled: false
    ehname: apimlogs
    storagecontainername: 
    ehconnstring: 
    storageconnstring: 
  aws:
    enabled: false
    kdsname: 
    region: 
    accesskeyid: 
    accesskeysecret: 
  logger:
    enabled: true
    rules: |
      include default
      skip_compression
    
kubernetes-ingress:
  controller:
    service:
      type: LoadBalancer
      enablePorts:
        stat: false
  defaultBackend:
    enabled: false

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80
#544100452964.dkr.ecr.us-west-2.amazonaws.com