# Default values for Resurface
# This is a YAML-formatted file.

etoken:

size: orca
provider:

ingress:
  enabled: true
  importer:
    expose: true
    path: "/fluke"
  tls:
    enabled: false
    host:
    autoissue:
      enabled: true
      staging: true
      email:
    byoc:
      secretname:
      cert:
      key:

custom:
  service:
    apiexplorer:
      port:
      type:
    flukeserver:
      port:
      type:
  resources:
    cpu:
    memory: 
  config:
    dbsize:
    dbheap:
    dbslabs:
  storage:
    size:
    classname:

multinode:
  enabled: false
  workers: 1

sniffer:
  enabled: false
  port: 80
  logger:
    enabled: true
    rules: |
      include default
      skip_compression

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80
