# Default values for Resurface
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  port:
    apiExplorer: 7700
    flukeServer: 7701

entitlementToken:

# multinode:
#   enabled: true
#   replicaCount: 2

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80
