# Default values for Resurface
# This is a YAML-formatted file.

provider:

ingress:
  enabled: true
  controller:
    enabled: true
  importer:
    expose: true
    path: "/fluke"
  tls:
    enabled: false
    host: 
    autoissue:
      enabled: true
      staging: true
      email: 
    byoc:
      secretname:

auth:
  enabled: false
  basic:
    enabled: false
    credentials:
      - username: 
        password: 
  jwt:
    enabled: false
    jwksurl: 
  oauth2:
    enabled: false
    issuer: 
    authurl: 
    tokenurl: 
    jwksurl: 
    userinfourl: 
    clientid: 
    clientsecret: 

multinode:
  enabled: false
  workers: 1

iceberg:
  enabled: false
  s3:
    enabled: false
    bucketname: iceberg.resurface
    aws:
      region:
      accesskey:
      secretkey:
  config:
    format:
    codec:
    millis:

custom:
  service:
    apiexplorer:
      port:
      type:
    flukeserver:
      port:
      type:
  resources:
    cpu:
    memory:
  config:
    dbsize:
    dbheap:
    dbslabs:
    shardsize:
    pollingcycle:
    tz:
  storage:
    size:
    classname:

sniffer:
  enabled: false
  discovery:
    enabled: false
    skip:
      ns: [ "kube-system" ]
      svc: [ "kubernetes" ]
  services:
  pods:
  labels:
  vpcmirror:
    enabled: false
    vnis:
    ports:
  logger:
    enabled: true
    rules: |
      include default
      skip_compression

consumer:
  azure:
    enabled: false
    ehname: apimlogs
    storagecontainername: 
    ehconnstring: 
    storageconnstring: 
  aws:
    enabled: false
    kdsname: 
    region: 
    accesskeyid: 
    accesskeysecret: 
  logger:
    enabled: true
    rules: |
      include default
      skip_compression

# Dependency chart: HAProxy Ingress Controller
kubernetes-ingress:
  controller:
    service:
      type: LoadBalancer
      enablePorts:
        stat: false
  defaultBackend:
    enabled: false

# Dependency chart: MinIO Object Storage
minio:
  enabled: false
  existingSecret: resurface-s3-creds
  rootUser: minio
  rootPassword: minio123
  mode: distributed
  replicas: 4
  persistence:
    size: 500Gi
  resources:
    requests:
      memory: 16Gi
  buckets:
    - name: iceberg.resurface
  securityContext:
    enabled: true
    runAsUser: 1000660000
    runAsGroup: 1000660000
    fsGroup: 1000660000
  configPathmc: "/tmp/minio/mc/"

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80
#544100452964.dkr.ecr.us-west-2.amazonaws.com