# Default values for Resurface
# This is a YAML-formatted file.

provider:

ingress:
  enabled: true
  importer:
    expose: true
    path: "/fluke"
  tls:
    enabled: false
    host:
    autoissue:
      enabled: true
      staging: true
      email:
    byoc:
      secretname:

custom:
  service:
    apiexplorer:
      port:
      type:
    flukeserver:
      port:
      type:
  resources:
    cpu:
    memory:
  config:
    dbsize:
    dbheap:
    dbslabs:
    tz:
  storage:
    size:
    classname:

multinode:
  enabled: false
  workers: 1

sniffer:
  enabled: false
  discovery:
    enabled: false
    skip:
      ns: [ "kube-system" ]
      svc: [ "kubernetes" ]
  services:
  pods:
  labels:
  logger:
    enabled: true
    rules: |
      include default
      skip_compression

listener:
  azure:
    ehconnstring: EHCONNSTRING
    ehname: EHNAME
    storageconnstring: STORAGECONNSTRING
    storagecontainername: STORAGECONTAINERNAME
  aws:
    kdsname: STREAMNAME
    region: us-west-2
    accesskeyid: SOMEKEY
    accesskeysecret: SHH
  logger:
    enabled: true
    rules: |
      include default
      skip_compression
    

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80
