# Default values for Resurface
# This is a YAML-formatted file.

provider:

ingress:
  enabled: true
  importer:
    expose: true
    path: "/fluke"
  tls:
    enabled: false
    host: 
    autoissue:
      enabled: true
      staging: true
      email: 
    byoc:
      secretname:

auth:
  enabled: false
  basic:
    enabled: false
    credentials:
      - username: 
        password: 
  jwt:
    enabled: false
    jwksurl: 
  oauth2:
    enabled: false
    issuer: 
    authurl: 
    tokenurl: 
    jwksurl: 
    userinfourl: 
    clientid: 
    clientsecret: 

multinode:
  enabled: false
  workers: 1

custom:
  service:
    apiexplorer:
      port:
      type:
    flukeserver:
      port:
      type:
  resources:
    cpu:
    memory:
  config:
    dbsize:
    dbheap:
    dbslabs:
    tz:
  storage:
    size:
    classname:

sniffer:
  enabled: false
  discovery:
    enabled: false
    skip:
      ns: [ "kube-system" ]
      svc: [ "kubernetes" ]
  services:
  pods:
  labels:
  logger:
    enabled: true
    rules: |
      include default
      skip_compression

consumer:
  azure:
    enabled: false
    ehname: apimlogs
    storagecontainername: 
    ehconnstring: 
    storageconnstring: 
  aws:
    enabled: false
    kdsname: 
    region: 
    accesskeyid: 
    accesskeysecret: 
  logger:
    enabled: true
    rules: |
      include default
      skip_compression
    

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80
