# Default values for Resurface
# This is a YAML-formatted file.

entitlementToken:

size: "orca"
provider: "azure"

service:
  ingress:
    enabled: false
    tls:
      enabled: false
      host:
      autoissue:
        enabled: true
        staging: true
        email:
      secretName:
  apiExplorer:
    port: 7700
    type: ClusterIP
  flukeServer:
    port: 7701

custom:
  resources:
    cpu:
    memory: 
  config:
    dbsize:
    dbheap:
    dbslabs:
  storage:
    size:
    className:

multinode:
  enabled: true
  workers: 2

sniffer:
  enabled: false
  port: 80
  logger:
    enabled: true
    rules: |
      include default
      skip_compression

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80
