# Default values for Resurface
# This is a YAML-formatted file.

provider:
units: binary

ingress:
  enabled: true
  controller:
    enabled: true
  importer:
    expose: true
    path: "/fluke"
  tls:
    enabled: false
    host: 
    autoissue:
      enabled: true
      staging: true
      email: 
    byoc:
      secretname:

auth:
  enabled: false
  basic:
    enabled: false
    credentials:
      - username: 
        password: 
  jwt:
    enabled: false
    jwksurl: 
  oauth2:
    enabled: false
    issuer: 
    authurl: 
    tokenurl: 
    jwksurl: 
    userinfourl: 
    clientid: 
    clientsecret: 

multinode:
  enabled: false
  workers: 1

iceberg:
  enabled: false
  s3:
    enabled: false
    bucketname:
    aws:
      region:
      accesskey:
      secretkey:
  config:
    format: PARQUET
    codec: ZSTD
    millis: 20000
    size:
      max: 100
      reserved: 20

custom:
  service:
    apiexplorer:
      port:
      type:
    flukeserver:
      port:
      type:
  resources:
    cpu:
    memory:
  config:
    dbsize:
    dbheap:
    dbslabs:
    shardsize:
    pollingcycle:
    tz:
  storage:
    size:
    classname:

sniffer:
  enabled: false
  discovery:
    enabled: false
    skip:
      ns: [ "kube-system" ]
      svc: [ "kubernetes" ]
  services:
  pods:
  labels:
  vpcmirror:
    enabled: false
    ports:
    vnis:
    autosetup:
      enabled: false
      schedule: "0 * * * *"
      source:
        ecs:
          clusters:
        ec2:
          instances:
          autoscaling:
      target:
        eks:
          cluster:
          nodegroup:
        sg:
        id:
      filter:
        id:
  logger:
    enabled: true
    rules: |
      include default
      skip_compression

consumer:
  azure:
    enabled: false
    ehname: apimlogs
    storagecontainername: 
    ehconnstring: 
    storageconnstring: 
  aws:
    enabled: false
    kdsname: 
    region: 
    accesskeyid: 
    accesskeysecret: 
    accesskey:
      enabled:
  logger:
    enabled: true
    rules: |
      include default
      skip_compression

# Dependency chart: HAProxy Ingress Controller
kubernetes-ingress:
  controller:
    service:
      type: LoadBalancer
      enablePorts:
        stat: false
      externalTrafficPolicy: Local
  defaultBackend:
    enabled: true

# Dependency chart: MinIO Object Storage
minio:
  enabled: false
  rootUser:
  rootPassword:
  mode: standalone
  replicas: 1
  persistence:
    size: 100Gi
  resources:
    requests:
      memory: 16Gi
  buckets:
    - name: iceberg.resurface
  securityContext:
    enabled: true
    runAsUser: 1000660000
    runAsGroup: 1000660000
    fsGroup: 1000660000
  configPathmc: "/tmp/minio/mc/"

qa:
  enabled: false
  simulator:
    enabled: false
    version:
    workload:
    host:
    port:
    limit:
      messages:
      millis:
    sleep:
      init:
      batch:
  importer:

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80
#544100452964.dkr.ecr.us-west-2.amazonaws.com