# Default values for Resurface
# This is a YAML-formatted file.

entitlementToken:

size: "orca"

service:
  ingress:
    enabled: false
    tls: false
  apiExplorer:
    port: 7700
    type: ClusterIP
  flukeServer:
    port: 7701

custom:
  resources:
    cpu: 4
    memory: 8
  config:
    dbsize:
    dbheap:
    dbslabs:

storage:
  volatile: false
  provider: "azure"
  coordinatorSize: 5Gi
  workerSize: 4Gi

multinode:
  enabled: true
  workers: 2

sniffer:
  enabled: false
  port: 80
  logger:
    enabled: true
    rules: |
      include default
      skip_compression

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80
