# Default values for Resurface
# This is a YAML-formatted file.

entitlementToken:

service:
  apiExplorer:
    port: 7700
    type: ClusterIP
  flukeServer:
    port: 7701

sniffer:
  deploy: false
  port: 80
  logger:
    enabled: true
    rules: |
      include default
      skip_compression

workers: 1

storage:
  provider: "azure"
  coordinatorSize: 5Gi
  workerSize: 4Gi


# multinode:
#   enabled: true
#   replicaCount: 2

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80
