name: Release Charts

on:
  push:
    branches:
      - v3.1.x
    paths:
      - helm/resurfaceio/**
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: helm/resurfaceio
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Checkout 2
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Move index.yaml
        run: |
          git checkout --progress --force -B gh-pages origin/gh-pages
          git mv -f index.yaml docs/index.yaml
          git commit -m "chore(helm): Update docs/index.yaml"
          git rebase v3.1.x
          git push origin +gh-pages
